name: Deploy Backend API

on:
  # Disabled auto-deploy until infrastructure is set up
  # push:
  #   branches:
  #     - main
  #     - dev
  #   paths:
  #     - 'backend/**'
  #     - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./backend/global.json

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend/SongsterGame.Api

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./backend/SongsterGame.Api

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish
        working-directory: ./backend/SongsterGame.Api

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-songster-${{ github.event.inputs.environment || 'dev' }}
          package: ./backend/SongsterGame.Api/publish

      - name: Deployment summary
        run: |
          echo "### Backend Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "App Service: app-songster-api-${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "URL: https://app-songster-api-${{ github.event.inputs.environment || 'dev' }}.azurewebsites.net" >> $GITHUB_STEP_SUMMARY
