name: Deploy Backend API

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    env:
      DOTNET_VERSION: '9.0.x'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend/SongsterGame.Api

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./backend/SongsterGame.Api

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish
        working-directory: ./backend/SongsterGame.Api

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-songster-api-${{ github.event.inputs.environment || 'dev' }}
          package: ./backend/SongsterGame.Api/publish

      - name: Deployment summary
        run: |
          echo "### Backend Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "App Service: app-songster-api-${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "URL: https://app-songster-api-${{ github.event.inputs.environment || 'dev' }}.azurewebsites.net" >> $GITHUB_STEP_SUMMARY
