name: Deploy Frontend to Dev

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-dev-frontend.yml'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: dev

    env:
      NODE_VERSION: '20.x'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend
        env:
          VITE_API_URL: https://app-songster-api-dev.azurewebsites.net
          VITE_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/frontend/dist'
          api_location: ''
          output_location: ''
          skip_app_build: true

      - name: Frontend deployment summary
        run: |
          echo "### Frontend Deployment Complete (Dev)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Environment: dev" >> $GITHUB_STEP_SUMMARY
          echo "Static Web App: stapp-songster-web-dev" >> $GITHUB_STEP_SUMMARY
